#!/bin/bash
# FastAPI + Dapr Service Generator
# Generates a new FastAPI microservice with Dapr integration

set -e

SERVICE_NAME=${1:-"my-service"}
SERVICE_PORT=${2:-8000}

echo "Generating FastAPI + Dapr service: $SERVICE_NAME"

# Create service directory
mkdir -p "src/backend/services/$SERVICE_NAME"

# Generate main.py
cat > "src/backend/services/$SERVICE_NAME/main.py" << 'EOF'
"""
FastAPI + Dapr Service
Auto-generated by fastapi-dapr-agent skill
"""
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import httpx
import os

app = FastAPI(
    title="SERVICE_NAME_PLACEHOLDER Service",
    description="AI-powered tutoring service with Dapr integration",
    version="1.0.0"
)

DAPR_HTTP_PORT = os.getenv("DAPR_HTTP_PORT", "3500")
STATE_STORE_NAME = os.getenv("STATE_STORE_NAME", "statestore")
PUBSUB_NAME = os.getenv("PUBSUB_NAME", "pubsub")

class HealthResponse(BaseModel):
    status: str
    service: str

@app.get("/health", response_model=HealthResponse)
async def health_check():
    """Health check endpoint for Kubernetes probes"""
    return HealthResponse(status="healthy", service="SERVICE_NAME_PLACEHOLDER")

@app.get("/ready")
async def readiness_check():
    """Readiness check for Kubernetes probes"""
    return {"ready": True}

# Add your service-specific endpoints here

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=SERVICE_PORT_PLACEHOLDER)
EOF

# Replace placeholders
sed -i "s/SERVICE_NAME_PLACEHOLDER/$SERVICE_NAME/g" "src/backend/services/$SERVICE_NAME/main.py"
sed -i "s/SERVICE_PORT_PLACEHOLDER/$SERVICE_PORT/g" "src/backend/services/$SERVICE_NAME/main.py"

# Generate Dockerfile
cat > "src/backend/services/$SERVICE_NAME/Dockerfile" << EOF
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE $SERVICE_PORT
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "$SERVICE_PORT"]
EOF

# Generate requirements.txt
cat > "src/backend/services/$SERVICE_NAME/requirements.txt" << 'EOF'
fastapi>=0.100.0
uvicorn>=0.22.0
httpx>=0.24.0
pydantic>=2.0.0
openai>=1.0.0
EOF

echo "✓ FastAPI + Dapr service '$SERVICE_NAME' generated successfully"
echo "  Location: src/backend/services/$SERVICE_NAME/"
echo "  Next: Run './scripts/deploy_dapr.sh $SERVICE_NAME' to deploy"
